/**
 * Typed API client methods for Google Jules REST endpoints.
 * @module client/jules_api
 */

import { getApiKey, request } from './http';
import { loadSessions } from '../core/storage';
import { JulesSource, SessionRecord } from '../core/types';

export { JulesSource, SessionRecord };

/**
 * Returns the tracked sessions loaded from local state persistence.
 *
 * @param targetDir - The root project directory containing the `.jules-companion` folder.
 * @returns An array of parsed SessionRecord objects.
 */
export function getSessions(targetDir: string = process.cwd()): SessionRecord[] {
  return loadSessions(targetDir);
}

/**
 * Cancels an active or queued Google Jules cloud session via HTTP DELETE.
 *
 * @param sessionId - The unique ID of the target session to cancel.
 * @param targetDir - Optional directory context to resolve API credentials.
 * @returns A promise resolving to the API response object.
 * @throws {Error} Throws an error if API key is missing or request fails.
 */
export async function cancelSessionApi(sessionId: string, targetDir?: string): Promise<any> {
  const apiKey = getApiKey(targetDir);
  if (!apiKey) throw new Error('JULES_API_KEY not found in environment or .env file.');
  const headers = { 'X-Goog-Api-Key': apiKey };
  return await request(`https://jules.googleapis.com/v1alpha/sessions/${sessionId}`, {
    method: 'DELETE',
    headers
  });
}

/**
 * Sends an interactive prompt reply or follow-up instruction to a running session.
 *
 * @param sessionId - The unique ID of the target session.
 * @param message - The message text to post to the session.
 * @param targetDir - Optional directory context to resolve API credentials.
 * @returns A promise resolving to the API response object.
 * @throws {Error} Throws an error if API key is missing or request fails.
 */
export async function sendMessageApi(sessionId: string, message: string, targetDir?: string): Promise<any> {
  const apiKey = getApiKey(targetDir);
  if (!apiKey) throw new Error('JULES_API_KEY not found in environment or .env file.');
  const headers = { 'X-Goog-Api-Key': apiKey };
  return await request(
    `https://jules.googleapis.com/v1alpha/sessions/${sessionId}:sendMessage`,
    {
      method: 'POST',
      headers
    },
    { prompt: message }
  );
}

/**
 * Fetches the list of active GitHub cloud sources configured for this Google Jules account.
 *
 * @param targetDir - Optional directory context to resolve API credentials.
 * @returns A promise resolving to an array of Jules sources.
 * @throws {Error} Throws an error if API key is missing or request fails.
 */
export async function listSourcesApi(targetDir?: string): Promise<JulesSource[]> {
  const apiKey = getApiKey(targetDir);
  if (!apiKey) throw new Error('JULES_API_KEY not found in environment or .env file.');
  const headers = { 'X-Goog-Api-Key': apiKey };
  const data = await request('https://jules.googleapis.com/v1alpha/sources', { headers });
  return data.sources || [];
}

/**
 * Traverses activities for a session and extracts the raw unidiff patch string generated by the agent.
 *
 * @param sessionId - The target session ID to extract patch from.
 * @param targetDir - Optional directory context to resolve API credentials.
 * @returns A promise resolving to the extracted unidiff patch string.
 * @throws {Error} Throws an error if no unidiff patch is found in session activities.
 */
export async function pullDiffApi(sessionId: string, targetDir?: string): Promise<string> {
  const apiKey = getApiKey(targetDir);
  if (!apiKey) throw new Error('JULES_API_KEY not found in environment or .env file.');
  const headers = { 'X-Goog-Api-Key': apiKey };
  const data = await request(`https://jules.googleapis.com/v1alpha/sessions/${sessionId}/activities`, { headers });
  const activities = data.activities || [];
  for (const act of activities) {
    if (act.artifacts) {
      for (const art of act.artifacts) {
        if (art.changeSet && art.changeSet.gitPatch && art.changeSet.gitPatch.unidiffPatch) {
          return art.changeSet.gitPatch.unidiffPatch;
        }
      }
    }
  }
  throw new Error(`No git patch found in activities for session ${sessionId}`);
}
