/**
 * Common utility and shared orchestration functions for Jules Companion.
 * @module utils
 */

import * as fs from 'fs';
import * as path from 'path';
import { spawnSync } from 'child_process';
import { runGit, GitExecutionResult } from './core/git';
import { getProjectDirs, loadSessions, saveSessions } from './core/storage';
import { ProjectDirs, SessionRecord } from './core/types';

export {
  ProjectDirs,
  SessionRecord,
  GitExecutionResult,
  runGit,
  getProjectDirs,
  loadSessions,
  saveSessions
};

/**
 * Parses command-line arguments into a key-value dictionary.
 * Supports boolean flags (e.g., `--all`) and key-value pairs (e.g., `--session 123`).
 *
 * @param args - An array of raw string arguments (typically process.argv.slice(2)).
 * @returns A dictionary where keys are argument names (without '--') and values are either strings or booleans.
 */
export function parseArgs(args: string[]): Record<string, string | boolean> {
  const params: Record<string, string | boolean> = {};
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--')) {
      const key = args[i].slice(2);
      const value = args[i + 1];

      if (value && !value.startsWith('--')) {
        params[key] = value;
        i++;
      } else {
        params[key] = true;
      }
    }
  }
  return params;
}

/**
 * Returns the provided date (or current date) formatted as DD-MM-YYYY.
 * e.g., 03-08-2026
 *
 * @param date - Optional Date object (defaults to current system date)
 * @returns Formatted date string in DD-MM-YYYY format
 */
export function getFormattedDateDDMMYYYY(date: Date = new Date()): string {
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  return `${day}-${month}-${date.getFullYear()}`;
}

/**
 * Intercepts stdout/stderr during CLI executions to prevent stdio stream corruption in MCP servers.
 *
 * @param fn - Execution callback to capture.
 * @returns Combined captured output string.
 */
export async function captureOutput(fn: () => Promise<any> | any): Promise<string> {
  const originalStdoutWrite = process.stdout.write;
  const originalStderrWrite = process.stderr.write;
  let buffer = '';

  process.stdout.write = (chunk: any) => {
    buffer += chunk.toString();
    return true;
  };
  process.stderr.write = (chunk: any) => {
    buffer += chunk.toString();
    return true;
  };

  try {
    await fn();
  } finally {
    process.stdout.write = originalStdoutWrite;
    process.stderr.write = originalStderrWrite;
  }

  return buffer.trim();
}

/**
 * Runs comprehensive diagnostic environment integrity checks.
 *
 * @param targetDir - Target project directory path (defaults to current working directory).
 * @returns Diagnostic check results mapping status strings.
 */
export function runDoctorChecks(targetDir: string = process.cwd()): { ok: boolean; checks: Record<string, string> } {
  const checks: Record<string, string> = {};
  let ok = true;

  // 1. Check Git remote origin configuration
  const gitRes = runGit(['config', '--get', 'remote.origin.url'], targetDir);
  if (gitRes.success && gitRes.stdout) {
    checks['git_remote'] = `OK: ${gitRes.stdout}`;
  } else {
    checks['git_remote'] = 'FAIL: No git remote origin URL configured';
    ok = false;
  }

  // 2. Check GitHub CLI (gh) availability
  const ghRes = spawnSync('gh', ['--version'], { encoding: 'utf8' });
  if (ghRes.status === 0) {
    checks['gh_cli'] = `OK: ${ghRes.stdout.split('\n')[0]}`;
  } else {
    checks['gh_cli'] = 'WARN: GitHub CLI (gh) not installed or not in PATH';
  }

  // 3. Check Node.js version
  checks['node_version'] = `OK: ${process.version}`;

  // 4. Check JULES_API_KEY presence in environment or local .env
  const envPath = path.join(targetDir, '.env');
  const companionEnvPath = path.join(targetDir, '.jules-companion', '.env');
  const hasEnvKey = !!process.env.JULES_API_KEY || fs.existsSync(envPath) || fs.existsSync(companionEnvPath);
  if (hasEnvKey) {
    checks['api_key'] = 'OK: JULES_API_KEY configured';
  } else {
    checks['api_key'] = 'FAIL: JULES_API_KEY missing in environment or .env file';
    ok = false;
  }

  return { ok, checks };
}

/**
 * Reads critical learnings logged in `.jules/<agentName>.md`.
 *
 * @param agentName - The specialized agent identifier (e.g. 'annotator').
 * @param targetDir - Target project directory path (defaults to current working directory).
 * @returns The raw markdown contents of the agent journal.
 */
export function readAgentJournal(agentName: string, targetDir: string = process.cwd()): string {
  const journalPath = path.join(targetDir, '.jules', `${agentName.toLowerCase()}.md`);
  if (!fs.existsSync(journalPath)) {
    return `# ${agentName} Journal\n\nNo critical learnings logged yet.`;
  }
  return fs.readFileSync(journalPath, 'utf8');
}

/**
 * Scans `docs/jules-reviews/` for markdown review reports generated by agents in review mode.
 *
 * @param targetDir - Target project directory path (defaults to current working directory).
 * @returns List of review report metadata.
 */
export function getReviewReports(
  targetDir: string = process.cwd()
): Array<{ fileName: string; path: string; sizeBytes: number }> {
  const reviewsDir = path.join(targetDir, 'docs', 'jules-reviews');
  if (!fs.existsSync(reviewsDir)) return [];
  const files = fs.readdirSync(reviewsDir);
  return files
    .filter(f => f.endsWith('.md'))
    .map(f => {
      const fullPath = path.join(reviewsDir, f);
      const stat = fs.statSync(fullPath);
      return {
        fileName: f,
        path: fullPath,
        sizeBytes: stat.size
      };
    });
}

/**
 * Programmatically scaffolds a new custom specialized agent template file and updates `registry.json`.
 *
 * @param name - The lowercase unique identifier for the custom agent.
 * @param role - The human-readable title/role description.
 * @param directives - The core directives and execution instructions.
 * @param boundariesDo - List of allowed actions (Always do).
 * @param boundariesDont - List of forbidden actions (Never do).
 * @param targetDir - Target project directory path (defaults to current working directory).
 * @returns Object containing the path to the newly created agent template.
 */
export function createCustomAgentScaffold(
  name: string,
  role: string,
  directives: string,
  boundariesDo: string[],
  boundariesDont: string[],
  targetDir: string = process.cwd()
): { agentFile: string } {
  const dirs = getProjectDirs(targetDir);
  const normalizedName = name.toLowerCase().trim();
  const agentFilePath = path.join(dirs.agentsDir, `${normalizedName}.md`);
  fs.mkdirSync(dirs.agentsDir, { recursive: true });

  const dosText = boundariesDo.map(d => `- ${d}`).join('\n');
  const dontsText = boundariesDont.map(d => `- ${d}`).join('\n');

  const content = `You are "${role}" 🤖 - a specialized agent for Jules Companion.

## Core Directives
${directives}

## Boundaries

✅ **Always do:**
${dosText}

🚫 **Never do:**
${dontsText}

## Daily Process
1. Analyze target source files.
2. Execute instructions cleanly.
3. Validate output before presentation.
`;

  fs.writeFileSync(agentFilePath, content, 'utf8');

  // Update local registry.json if exists
  const registryPath = path.join(dirs.agentsDir, 'registry.json');
  if (fs.existsSync(registryPath)) {
    try {
      const reg = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
      if (!reg.agents) reg.agents = {};
      reg.agents[normalizedName] = {
        name: role,
        group: 'Coding',
        description: directives.slice(0, 100)
      };
      fs.writeFileSync(registryPath, JSON.stringify(reg, null, 2), 'utf8');
    } catch (_) {}
  }

  return { agentFile: agentFilePath };
}
